import type {Metadata} from 'next'
import {Inter, Poppins} from 'next/font/google'
import './globals.css'
import Provider from "@/components/layout/provider/Provider";
import 'bootstrap/dist/css/bootstrap.css';
const inter = Inter({subsets: ['latin']})
const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {


    return (
        <html lang="en">
        <head>
            <title>VCR Menu</title>
        </head>

        <body className={poppins.className}>
        <Provider>
            {children}
        </Provider>
        </body>
        </html>
    )
}
